In [2]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

In [3]:
import scipy.stats

In [4]:
import stat_functions as st

In [5]:
%matplotlib inline

## Dataframes created so far:

**tracking** = covid 19 tracking data

**who_us_responses** = narrowed dataframe to US responses complete with dates enacted (for comparison)

**pop_state_estimate** = us census population estimates (as of July 2019, for purposes of calculating incidence rates)

**state_pop2020** - estimates of population by state based on growth projections, from 
World Population Review

## Cleaned Dataset

Called tracking_clean (to be imported for analysis file). Contains all of the tracking data info along with population estimates for each state in 2020. The WHO data is unfortunately not State specific, so is not likely to be useful for much beyond the start dates of national social distancing measures.

In [6]:
tracking = pd.read_csv('COVID tracking - Historical.csv')
#tracking = pd.read_csv('COVID tracking - Historical updated.csv')

In [7]:
tracking.columns = map(str.title, tracking.columns)

In [8]:
tracking.columns

Index(['People_Negative_New_Count', 'Province_State_Code',
       'People_Positive_Cases_Count', 'Data_Completeness_Score_Name',
       'Report_Date', 'People_In_Intensive_Care_Currently_Count',
       'People_Pending_Cases_Count', 'People_Recovered_Count',
       'Reported_Date_Time', 'People_Positive_Negative_Test_Results_Count',
       'Data_Source_Name', 'People_Death_New_Count',
       'People_Intubated_Cumulative_Count', 'People_Test_Results_New_Count',
       'People_In_Intensive_Care_Cumulative_Count',
       'People_Negative_Cases_Count', 'Province_State_Fips_Number',
       'People_Hospitalized_New_Count', 'People_Hospitalized_Cumulative_Count',
       'People_Intubated_Currently_Count',
       'People_Hospitalized_Currently_Count',
       'People_Positive_New_Cases_Count', 'People_Death_Count'],
      dtype='object')

In [9]:
tracking.Reported_Date_Time = tracking.Reported_Date_Time.apply(lambda x: pd.to_datetime(x))

In [10]:
tracking.head()

,People_Negative_New_Count,Province_State_Code,People_Positive_Cases_Count,Data_Completeness_Score_Name,Report_Date,People_In_Intensive_Care_Currently_Count,People_Pending_Cases_Count,People_Recovered_Count,Reported_Date_Time,People_Positive_Negative_Test_Results_Count,...,People_Test_Results_New_Count,People_In_Intensive_Care_Cumulative_Count,People_Negative_Cases_Count,Province_State_Fips_Number,People_Hospitalized_New_Count,People_Hospitalized_Cumulative_Count,People_Intubated_Currently_Count,People_Hospitalized_Currently_Count,People_Positive_New_Cases_Count,People_Death_Count
0,6568,AK,1631.0,A,7/15/2020,NaN,NaN,669.0,2020-07-15 00:00:00,156093,...,6620,NaN,154462.0,2,0,NaN,0.0,32.0,52,17.0
1,10148,AL,59067.0,B,7/15/2020,NaN,NaN,29736.0,2020-07-15 11:00:00,541049,...,11960,941.0,481982.0,1,168,7291.0,NaN,1362.0,1812,1211.0
2,4913,AR,30297.0,A,7/15/2020,NaN,NaN,23523.0,2020-07-15 14:36:00,395776,...,5477,NaN,365479.0,5,76,1948.0,94.0,458.0,564,335.0
3,0,AS,0.0,C,7/15/2020,NaN,NaN,NaN,2020-07-01 00:00:00,816,...,0,NaN,816.0,60,0,NaN,NaN,NaN,0,0.0
4,10762,AZ,131354.0,A+,7/15/2020,929.0,NaN,16155.0,2020-07-15 00:00:00,735962,...,14019,NaN,604608.0,4,161,6103.0,671.0,3493.0,3257,2434.0

In [11]:
tracking.Reported_Date_Time.describe()

count                    7065
unique                   3397
top       2020-06-01 00:00:00
freq                       43
first     2020-02-29 00:00:00
last      2020-07-15 18:02:00
Name: Reported_Date_Time, dtype: object

In [12]:
pop_by_state = pd.read_csv('nst-est2019-alldata.csv')

In [13]:
pop_by_state.columns = map(str.title, pop_by_state.columns)

In [14]:
pop_by_state.head()

,Sumlev,Region,Division,State,Name,Census2010Pop,Estimatesbase2010,Popestimate2010,Popestimate2011,Popestimate2012,...,Rdomesticmig2019,Rnetmig2011,Rnetmig2012,Rnetmig2013,Rnetmig2014,Rnetmig2015,Rnetmig2016,Rnetmig2017,Rnetmig2018,Rnetmig2019
0,10,0,0,0,United States,308745538,308758105,309321666,311556874,313830990,...,0.000000,2.493773,2.682083,2.636187,2.921500,3.260435,3.252788,2.871957,2.153911,1.818059
1,20,1,0,0,Northeast Region,55317240,55318443,55380134,55604223,55775216,...,-5.254530,0.887909,-0.038355,-0.469783,-0.986097,-2.061965,-2.490484,-1.837048,-2.134447,-2.859713
2,20,2,0,0,Midwest Region,66927001,66929725,66974416,67157800,67336743,...,-2.365881,-0.963930,-0.973943,-0.006924,-0.762969,-1.388437,-1.241784,-0.557370,-0.922755,-1.111173
3,20,3,0,0,South Region,114555744,114563030,114866680,116006522,117241208,...,3.261349,5.130513,5.850458,5.292073,6.161501,7.277358,7.150074,6.198168,5.225519,5.203720
4,20,4,0,0,West Region,71945553,71946907,72100436,72788329,73477823,...,0.614245,2.723344,3.062896,3.162262,4.026429,4.987285,5.261078,4.021194,3.044951,2.312083

In [15]:
pop_state_estimate = pop_by_state[['Name', 'Popestimate2019']]

In [16]:
pop_state_estimate['Name'] = pop_state_estimate['Name'].map({'United States':'Total US','Northeast Region':'Northeast Region',
                                                            'Midwest Region':'Midwest Region','South Region':'South Region',
                                                             'West Region':'West Region','Alabama':'AL','Alaska':'AK','Arizona':'AZ',
                                                           'Arkansas':'AR','California':'CA','Colorado':'CO',
                                                           'Connecticut':'CT','Delaware':'DE', 'District of Columbia':'Washington DC','Florida':'FL',
                                                           'Georgia':'GA','Hawaii':'HI','Idaho':'ID','Illinois':'IL',
                                                           'Indiana':'IN','Iowa':'IA','Kansas':'KS','Kentucky':'KY',
                                                           'Louisiana':'LA','Maine':'ME','Maryland':'MD',
                                                           'Massachusetts':'MA','Michigan':'MI','Minnesota':'MN',
                                                           'Mississippi':'MS','Missouri':'MO','Montana':'MT',
                                                           'Nebraska':'NE','Nevada':'NV','New Hampshire':'NH',
                                                           'New Jersey':'NJ','New Mexico':'NM','New York':'NY',
                                                           'North Carolina':'NC','North Dakota':'ND','Ohio':'OH',
                                                           'Oklahoma':'OK','Oregon':'OR','Pennsylvania':'PA',
                                                           'Rhode Island':'RI','South Carolina':'SC','South Dakota':'SD',
                                                           'Tennessee':'TN','Texas':'TX','Utah':'UT','Vermont':'VT',
                                                           'Virginia':'VA','Washington':'WA','West Virginia':'WV',
                                                           'Wisconsin':'WI','Wyoming':'WY'})

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
world_pop_review_us_pop = pd.read_csv('world_population_review_2020pop_state.csv')

In [18]:
state_pop2020 = world_pop_review_us_pop[['State', 'Pop']]

In [19]:
state_pop2020['State'] = state_pop2020['State'].map({'Alabama':'AL','Alaska':'AK','Arizona':'AZ',
                                                    'Arkansas':'AR','California':'CA','Colorado':'CO',
                                                'Connecticut':'CT','Delaware':'DE','District of Columbia':'DC',
                                                   'Florida':'FL','Georgia':'GA','Hawaii':'HI','Idaho':'ID',
                                                   'Illinois':'IL','Indiana':'IN','Iowa':'IA','Kansas':'KS',
                                                   'Kentucky':'KY','Louisiana':'LA','Maine':'ME','Maryland':'MD',
                                                   'Massachusetts':'MA','Michigan':'MI','Minnesota':'MN',
                                                   'Mississippi':'MS','Missouri':'MO','Montana':'MT',
                                                   'Nebraska':'NE','Nevada':'NV','New Hampshire':'NH',
                                                   'New Jersey':'NJ','New Mexico':'NM','New York':'NY',
                                                   'North Carolina':'NC','North Dakota':'ND','Ohio':'OH',
                                                   'Oklahoma':'OK','Oregon':'OR','Pennsylvania':'PA','Puerto Rico':'PR',
                                                   'Rhode Island':'RI','South Carolina':'SC','South Dakota':'SD',
                                                   'Tennessee':'TN','Texas':'TX','Utah':'UT','Vermont':'VT',
                                                   'Virginia':'VA','Washington':'WA','West Virginia':'WV',
                                                   'Wisconsin':'WI','Wyoming':'WY'})

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [20]:
state_pop2020.head()

  State       Pop
0    AL   4908620
1    AK    734002
2    AZ   7378490
3    AR   3039000
4    CA  39937500

In [21]:
state_pop2020.columns

Index(['State', 'Pop'], dtype='object')

In [22]:
state_pop2020.Pop.sum()

334351340

Above can be used to match populations to state abbreviations. This is helpful for rate of incidence calculations per state (probably in per 100,000).

In [23]:
tracking_april_on = tracking[tracking.Reported_Date_Time > '2020-04-01']

In [24]:
tracking_april_on['Month'] = tracking.Reported_Date_Time.apply(lambda x: x.month)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
pos_cases = tracking_april_on.groupby(['Province_State_Code', 'Month']).People_Positive_Cases_Count.sum().unstack()

In [26]:
pos_cases = pos_cases.reset_index()

In [27]:
pos_cases.rename(columns = {4.0:'April', 5.0:'May', 6.0:'June', 7.0:'July'}, inplace = True)

In [28]:
pos_cases['Positive_Cases_Since_April'] = pos_cases.apply(lambda row: row.April + row.May + row.June
                                                    + row.July, axis = 1)

In [29]:
pos_cases_w_pop = pd.merge(pos_cases, state_pop2020, how = 'left', left_on = 'Province_State_Code', right_on = 'State')

In [30]:
pos_cases_w_pop.drop(['State'], axis = 1)

,Province_State_Code,April,May,June,July,Positive_Cases_Since_April,Pop
0,AK,8140.0,12205.0,20384.0,19063.0,59792.0,734002.0
1,AL,121825.0,367602.0,799987.0,722461.0,2011875.0,4908620.0
2,AR,52392.0,149014.0,398698.0,382583.0,982687.0,3039000.0
3,AS,0.0,0.0,0.0,0.0,0.0,NaN
4,AZ,127241.0,417109.0,1292258.0,1626401.0,3463009.0,7378490.0
5,CA,849733.0,2359917.0,4756499.0,4322161.0,12288310.0,39937500.0
6,CO,274120.0,621073.0,913245.0,492116.0,2300554.0,5845530.0
7,CT,464322.0,1165724.0,1352489.0,659660.0,3642195.0,3563080.0
8,DC,75022.0,210304.0,302193.0,149428.0,736947.0,720687.0
9,DE,66518.0,239019.0,314506.0,174575.0,794618.0,982895.0
10,FL,661546.0,1395338.0,2796863.0,3258952.0,8112699.0,21993000.0
11,GA,462253.0,1153301.0,1822291.0,1574329.0,5012174.0,10736100.0
12,GU,3800.0,4896.0,6370.0,4233.0,19299.0,NaN
13,HI,15118.0,19741.0,22679.0,15279.0,72817.0,1412690.0
14,IA,91503.0,432123.0,728145.0,493289.0,1745060.0,3179850.0
15,ID,45715.0,74970.0,116475.0,124503.0,361663.0,1826160.0
16,IL,802317.0,2817378.0,4013814.0,2267102.0,9900611.0,12659700.0
17,IN,308228.0,854465.0,1221971.0,695420.0,3080084.0,6745350.0
18,KS,54501.0,236731.0,365343.0,248667.0,905242.0,2910360.0
19,KY,74634.0,221077.0,384127.0,269617.0,949455.0,4499690.0
20,LA,625160.0,1058343.0,1432634.0,1065839.0,4181976.0,4645180.0
21,MA,980427.0,2683390.0,3064060.0,1660304.0,8388181.0,6976600.0
22,MD,326302.0,1183128.0,1848484.0,1067172.0,4425086.0,6083120.0
23,ME,22358.0,54507.0,85002.0,48582.0,210449.0,1345790.0
24,MI,1036680.0,1766294.0,2001687.0,1120053.0,5924714.0,10045000.0
25,MN,101604.0,571259.0,952026.0,562351.0,2187240.0,5700670.0
26,MO,144456.0,330212.0,502252.0,380384.0,1357304.0,6169270.0
27,MP,348.0,589.0,921.0,414.0,2272.0,NaN
28,MS,115860.0,352612.0,624641.0,468181.0,1561294.0,2989260.0
29,MT,11900.0,14127.0,19791.0,21938.0,67756.0,1086760.0
30,NC,168564.0,571848.0,1375755.0,1175699.0,3291866.0,10611900.0
31,ND,14820.0,57707.0,93160.0,60608.0,226295.0,761723.0
32,NE,44275.0,305705.0,508005.0,285536.0,1143521.0,1952570.0
33,NH,37413.0,109321.0,159910.0,83234.0,389878.0,1371250.0
34,NJ,2186635.0,4470485.0,5010185.0,2611829.0,14279134.0,8936570.0
35,NM,45747.0,181396.0,298607.0,194548.0,720298.0,2096640.0
36,NV,97218.0,210852.0,364413.0,368475.0,1040958.0,3139660.0
37,NY,6228443.0,10693471.0,11907571.0,5591361.0,34420846.0,19440500.0
38,OH,285889.0,847464.0,1279993.0,910815.0,3324161.0,11747700.0
39,OK,67889.0,160501.0,277518.0,269662.0,775570.0,3954820.0
40,OR,49588.0,108405.0,183829.0,164549.0,506371.0,4301090.0
41,PA,801610.0,1883395.0,2387279.0,1383813.0,6456097.0,12820900.0
42,PR,28043.0,81742.0,174784.0,132106.0,416675.0,3032160.0
43,RI,130816.0,390081.0,484286.0,258725.0,1263908.0,1056160.0
44,SC,111739.0,268529.0,674393.0,707366.0,1762027.0,5210100.0
45,SD,36229.0,118992.0,177960.0,108736.0,441917.0,903027.0
46,TN,191357.0,539012.0,960306.0,845369.0,2536044.0,6897580.0
47,TX,471275.0,1430663.0,2998487.0,3347619.0,8248044.0,29472300.0
48,UT,82178.0,221281.0,461201.0,402920.0,1167580.0,3282120.0
49,VA,240788.0,953908.0,1662120.0,954185.0,3811001.0,8626210.0
50,VI,1536.0,2050.0,2230.0,2152.0,7968.0,NaN
51,VT,21465.0,29077.0,33550.0,18973.0,103065.0,628061.0
52,WA,372017.0,617459.0,862175.0,527589.0,2379240.0,7797100.0
53,WI,140734.0,436436.0,778455.0,553011.0,1908636.0,5851750.0
54,WV,20973.0,46996.0,71504.0,55437.0,194910.0,1778070.0
55,WY,9130.0,22937.0,32774.0,26034.0,90875.0,567025.0

In [31]:
tracking_pop = pd.merge(tracking,state_pop2020, how = 'left', left_on = 'Province_State_Code', right_on = 'State')

In [32]:
tracking_clean = tracking_pop.drop('State', axis = 1)

# Adding to merged Dataset

Having combined the COVID tracking data currently here with the most up to date population estimates for 2020 (calculated via data from US Census by the World Population Review), the following additions show prevalence/incidence rates. Most of these columns will reflect INCIDENCE rate for the period of 2020 as of July 15 (using total counts instead of NEW counts). If any are based only upon new data, they will be named specifically as prevalence since last report date.

In [33]:
tracking_clean['Month'] = tracking_clean.Reported_Date_Time.apply(lambda x: x.month)

In [34]:
tracking_clean['Day'] = tracking_clean.Reported_Date_Time.apply(lambda x: x.dayofyear)

In [55]:
tracking_clean['Deaths_per_100k'] = tracking_clean.apply(lambda row:row.People_Death_Count / row.Pop * 100000, axis = 1)

In [54]:
tracking_clean['Death_Rate'] = tracking_clean.apply(lambda row:row.People_Death_Count / row.Pop * 100, axis = 1)

In [37]:
tracking_clean['Total_Tested_Positive_per_100k'] = tracking_clean.apply(lambda row:row.People_Positive_Cases_Count / row.Pop * 100000, axis = 1)

In [38]:
tracking_clean['Hospitalizations_per_100k_Incidence'] = tracking_clean.apply\
(lambda row:row.People_Hospitalized_Currently_Count / row.Pop * 100000, axis = 1)

In [39]:
tracking_clean.head()

,People_Negative_New_Count,Province_State_Code,People_Positive_Cases_Count,Data_Completeness_Score_Name,Report_Date,People_In_Intensive_Care_Currently_Count,People_Pending_Cases_Count,People_Recovered_Count,Reported_Date_Time,People_Positive_Negative_Test_Results_Count,...,People_Hospitalized_Currently_Count,People_Positive_New_Cases_Count,People_Death_Count,Pop,Month,Day,Deaths_per_100k,Death_Rate,Total_Tested_Positive_per_100k,Hospitalizations_per_100k_Incidence
0,6568,AK,1631.0,A,7/15/2020,NaN,NaN,669.0,2020-07-15 00:00:00,156093,...,32.0,52,17.0,734002.0,7.0,197.0,2.316070,0.002316,222.206479,4.359661
1,10148,AL,59067.0,B,7/15/2020,NaN,NaN,29736.0,2020-07-15 11:00:00,541049,...,1362.0,1812,1211.0,4908620.0,7.0,197.0,24.670885,0.024671,1203.332097,27.747106
2,4913,AR,30297.0,A,7/15/2020,NaN,NaN,23523.0,2020-07-15 14:36:00,395776,...,458.0,564,335.0,3039000.0,7.0,197.0,11.023363,0.011023,996.939783,15.070747
3,0,AS,0.0,C,7/15/2020,NaN,NaN,NaN,2020-07-01 00:00:00,816,...,NaN,0,0.0,NaN,7.0,183.0,NaN,NaN,NaN,NaN
4,10762,AZ,131354.0,A+,7/15/2020,929.0,NaN,16155.0,2020-07-15 00:00:00,735962,...,3493.0,3257,2434.0,7378490.0,7.0,197.0,32.987779,0.032988,1780.228746,47.340309

In [40]:
tracking_clean.columns

Index(['People_Negative_New_Count', 'Province_State_Code',
       'People_Positive_Cases_Count', 'Data_Completeness_Score_Name',
       'Report_Date', 'People_In_Intensive_Care_Currently_Count',
       'People_Pending_Cases_Count', 'People_Recovered_Count',
       'Reported_Date_Time', 'People_Positive_Negative_Test_Results_Count',
       'Data_Source_Name', 'People_Death_New_Count',
       'People_Intubated_Cumulative_Count', 'People_Test_Results_New_Count',
       'People_In_Intensive_Care_Cumulative_Count',
       'People_Negative_Cases_Count', 'Province_State_Fips_Number',
       'People_Hospitalized_New_Count', 'People_Hospitalized_Cumulative_Count',
       'People_Intubated_Currently_Count',
       'People_Hospitalized_Currently_Count',
       'People_Positive_New_Cases_Count', 'People_Death_Count', 'Pop', 'Month',
       'Day', 'Deaths_per_100k', 'Death_Rate',
       'Total_Tested_Positive_per_100k',
       'Hospitalizations_per_100k_Incidence'],
      dtype='object')

In [41]:
tracking_clean.Data_Source_Name.unique()

array(['COVID Tracking Project Historical'], dtype=object)

In [42]:
#tracking_clean.People_Test_Results_New_Count.head(15)

In [43]:
columns_names = ['Data_Completeness_Score_Name','People_Positive_New_Cases_Count',
                               'People_Positive_Cases_Count','People_Negative_New_Count','People_Negative_Cases_Count',
                               'People_Test_Results_New_Count','People_Pending_Cases_Count',
                                 'Total_Tested_Positive_per_100k',
                                'People_Positive_Negative_Test_Results_Count','People_Hospitalized_New_Count',
                               'People_Hospitalized_Currently_Count','People_Hospitalized_Cumulative_Count',
                                 'Hospitalizations_per_100k_Incidence',
                                'People_In_Intensive_Care_Currently_Count','People_In_Intensive_Care_Cumulative_Count',
                                'People_Intubated_Currently_Count','People_Intubated_Cumulative_Count',
                                'People_Death_New_Count','People_Death_Count','Deaths_per_100k','Death_Rate',
                                 'People_Recovered_Count','Report_Date','Reported_Date_Time',
                                 'Day','Month','Province_State_Code', 'Pop']
tracking_clean = tracking_clean.reindex(columns = columns_names)

In [44]:
as_indices = tracking_clean[tracking_clean.Province_State_Code == 'AS'].index.tolist()

In [45]:
for i in as_indices:
    tracking_clean.Pop.loc[i] = 55183.0
#tracking_clean.loc[indices[2]]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [46]:
gu_indices = tracking_clean[tracking_clean.Province_State_Code == 'GU'].index.tolist()

In [47]:
for i in gu_indices:
    tracking_clean.Pop.loc[i] = 168775.0

In [48]:
mp_indices = tracking_clean[tracking_clean.Province_State_Code == 'MP'].index.tolist()

In [49]:
for i in mp_indices:
    tracking_clean.Pop.loc[i] = 57580.0

In [50]:
vi_indices = tracking_clean[tracking_clean.Province_State_Code == 'VI'].index.tolist()

In [51]:
for i in vi_indices:
    tracking_clean.Pop.loc[i] = 104425.0

In [56]:
tracking_clean.head(53)

,Data_Completeness_Score_Name,People_Positive_New_Cases_Count,People_Positive_Cases_Count,People_Negative_New_Count,People_Negative_Cases_Count,People_Test_Results_New_Count,People_Pending_Cases_Count,Total_Tested_Positive_per_100k,People_Positive_Negative_Test_Results_Count,People_Hospitalized_New_Count,...,People_Death_Count,Deaths_per_100k,Death_Rate,People_Recovered_Count,Report_Date,Reported_Date_Time,Day,Month,Province_State_Code,Pop
0,A,52,1631.0,6568,154462.0,6620,NaN,222.206479,156093,0,...,17.0,2.316070,0.002316,669.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,AK,734002.0
1,B,1812,59067.0,10148,481982.0,11960,NaN,1203.332097,541049,168,...,1211.0,24.670885,0.024671,29736.0,7/15/2020,2020-07-15 11:00:00,197.0,7.0,AL,4908620.0
2,A,564,30297.0,4913,365479.0,5477,NaN,996.939783,395776,76,...,335.0,11.023363,0.011023,23523.0,7/15/2020,2020-07-15 14:36:00,197.0,7.0,AR,3039000.0
3,C,0,0.0,0,816.0,0,NaN,NaN,816,0,...,0.0,0.000000,0.000000,NaN,7/15/2020,2020-07-01 00:00:00,183.0,7.0,AS,55183.0
4,A+,3257,131354.0,10762,604608.0,14019,NaN,1780.228746,735962,161,...,2434.0,32.987779,0.032988,16155.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,AZ,7378490.0
5,B,11126,347634.0,107195,5445642.0,118321,NaN,870.445070,5793276,0,...,7227.0,18.095775,0.018096,NaN,7/15/2020,2020-07-15 00:00:00,197.0,7.0,CA,39937500.0
6,A,444,37686.0,4591,372304.0,5035,NaN,644.697743,409990,22,...,1594.0,27.268699,0.027269,4844.0,7/15/2020,2020-07-15 01:59:00,197.0,7.0,CO,5845530.0
7,B,106,47636.0,12232,556463.0,12338,NaN,1336.933215,604099,0,...,4380.0,122.927355,0.122927,8351.0,7/15/2020,2020-07-14 20:30:00,196.0,7.0,CT,3563080.0
8,A+,80,11026.0,3948,126918.0,4028,NaN,1529.929082,137944,0,...,571.0,79.229957,0.079230,1809.0,7/15/2020,2020-07-14 00:00:00,196.0,7.0,DC,720687.0
9,A+,81,13050.0,1707,130338.0,1788,NaN,1327.710488,143388,0,...,521.0,53.006679,0.053007,7236.0,7/15/2020,2020-07-14 18:00:00,196.0,7.0,DE,982895.0
10,A,10181,301810.0,40529,2434143.0,50710,2189.0,1372.300277,2735953,458,...,4626.0,21.033965,0.021034,NaN,7/15/2020,2020-07-14 23:59:00,196.0,7.0,FL,21993000.0
11,A,3871,127834.0,20078,1027149.0,23949,NaN,1190.693082,1154983,417,...,3091.0,28.790715,0.028791,NaN,7/15/2020,2020-07-15 14:50:00,197.0,7.0,GA,10736100.0
12,B,1,313.0,289,17514.0,290,NaN,NaN,17827,0,...,5.0,2.962524,0.002963,213.0,7/15/2020,2020-07-14 22:15:00,196.0,7.0,GU,168775.0
13,D,21,1264.0,1466,96293.0,1487,NaN,89.474690,97557,5,...,22.0,1.557313,0.001557,921.0,7/15/2020,2020-07-14 18:00:00,196.0,7.0,HI,1412690.0
14,A+,442,36291.0,6462,351021.0,6904,NaN,1141.280249,387312,0,...,762.0,23.963394,0.023963,27177.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,IA,3179850.0
15,A,316,11718.0,3314,122196.0,3630,NaN,641.674333,133914,10,...,103.0,5.640251,0.005640,3360.0,7/15/2020,2020-07-14 19:00:00,196.0,7.0,ID,1826160.0
16,A,1187,157825.0,36974,1922908.0,38161,NaN,1246.672512,2080733,0,...,7427.0,58.666477,0.058666,NaN,7/15/2020,2020-07-15 00:00:00,197.0,7.0,IL,12659700.0
17,A+,685,53370.0,7495,533219.0,8180,NaN,791.211724,586589,53,...,2785.0,41.287702,0.041288,39571.0,7/15/2020,2020-07-14 23:59:00,196.0,7.0,IN,6745350.0
18,A,875,20933.0,7324,218441.0,8199,NaN,719.258099,239374,50,...,299.0,10.273643,0.010274,948.0,7/15/2020,2020-07-15 10:00:00,197.0,7.0,KS,2910360.0
19,B,454,20677.0,3177,438510.0,3631,NaN,459.520545,459187,21,...,645.0,14.334321,0.014334,5475.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,KY,4499690.0
20,B,2089,84131.0,22656,917069.0,24745,NaN,1811.146177,1001200,0,...,3461.0,74.507339,0.074507,53288.0,7/15/2020,2020-07-15 13:00:00,197.0,7.0,LA,4645180.0
21,A+,217,112347.0,10282,876366.0,10499,NaN,1610.340280,988713,26,...,8368.0,119.943812,0.119944,95390.0,7/15/2020,2020-07-15 10:00:00,197.0,7.0,MA,6976600.0
22,A,756,75016.0,13263,605072.0,14019,NaN,1233.182972,680088,140,...,3341.0,54.922474,0.054922,5238.0,7/15/2020,2020-07-15 10:00:00,197.0,7.0,MD,6083120.0
23,A+,12,3578.0,2444,124353.0,2456,NaN,265.866146,127931,0,...,114.0,8.470861,0.008471,3079.0,7/15/2020,2020-07-14 23:59:00,196.0,7.0,ME,1345790.0
24,A+,1049,78913.0,33084,1289006.0,34133,NaN,785.594823,1367919,0,...,6330.0,63.016426,0.063016,53867.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,MI,10045000.0
25,A,572,43742.0,12311,746755.0,12883,NaN,767.313316,790497,43,...,1558.0,27.330121,0.027330,38179.0,7/15/2020,2020-07-14 17:00:00,196.0,7.0,MN,5700670.0
26,B,888,29714.0,11956,488233.0,12844,NaN,481.645316,517947,0,...,1102.0,17.862729,0.017863,NaN,7/15/2020,2020-07-15 15:00:00,197.0,7.0,MO,6169270.0
27,D,3,36.0,0,10664.0,3,NaN,NaN,10700,0,...,2.0,3.473428,0.003473,29.0,7/15/2020,2020-07-14 04:48:00,196.0,7.0,MP,57580.0
28,A,1025,38567.0,5619,318290.0,6644,NaN,1290.185531,356857,44,...,1290.0,43.154493,0.043154,25932.0,7/15/2020,2020-07-14 19:00:00,196.0,7.0,MS,2989260.0
29,C,144,2096.0,2218,121662.0,2362,NaN,192.866870,123758,9,...,34.0,3.128566,0.003129,915.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,MT,1086760.0
30,A,1782,91266.0,28009,1193371.0,29791,NaN,860.034490,1284637,0,...,1568.0,14.775865,0.014776,67124.0,7/15/2020,2020-07-15 12:00:00,197.0,7.0,NC,10611900.0
31,D,72,4565.0,1459,121999.0,1531,NaN,599.299220,126564,4,...,81.0,10.633787,0.010634,3760.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,ND,761723.0
32,B,318,21717.0,3190,198026.0,3508,NaN,1112.226450,219743,11,...,286.0,14.647362,0.014647,16205.0,7/15/2020,2020-07-14 20:05:00,196.0,7.0,NE,1952570.0
33,B,23,6091.0,1058,131018.0,1081,NaN,444.193254,137109,76,...,392.0,28.587056,0.028587,5101.0,7/15/2020,2020-07-14 09:00:00,196.0,7.0,NH,1371250.0
34,A+,363,176278.0,20753,1566069.0,21116,NaN,1972.546514,1742347,142,...,15607.0,174.641949,0.174642,31400.0,7/15/2020,2020-07-15 13:00:00,197.0,7.0,NJ,8936570.0
35,B,223,15514.0,5428,414492.0,5651,NaN,739.945818,430006,34,...,551.0,26.280143,0.026280,6429.0,7/15/2020,2020-07-14 18:04:00,196.0,7.0,NM,2096640.0
36,A+,849,30468.0,3396,333957.0,4245,NaN,970.423549,364425,0,...,618.0,19.683660,0.019684,826.0,7/15/2020,2020-07-15 13:00:00,197.0,7.0,NV,3139660.0
37,A,831,404006.0,62767,4444519.0,63598,NaN,2078.166714,4848525,0,...,25003.0,128.612947,0.128613,71782.0,7/15/2020,2020-07-14 23:59:00,196.0,7.0,NY,19440500.0
38,B,1316,69311.0,17558,993312.0,18874,NaN,589.996340,1062623,160,...,3075.0,26.175336,0.026175,47303.0,7/15/2020,2020-07-15 14:00:00,197.0,7.0,OH,11747700.0
39,A+,1075,22813.0,4956,424512.0,6031,NaN,576.840412,447325,54,...,432.0,10.923380,0.010923,17366.0,7/15/2020,2020-07-13 00:00:00,195.0,7.0,OK,3954820.0
40,A+,0,12805.0,0,292651.0,0,NaN,297.715230,305456,0,...,244.0,5.672981,0.005673,3129.0,7/15/2020,2020-07-14 03:01:00,196.0,7.0,OR,4301090.0
41,A+,994,97665.0,20372,870984.0,21366,NaN,761.763995,968649,0,...,6957.0,54.262961,0.054263,74436.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,PA,12820900.0
42,B,256,10379.0,0,192686.0,256,NaN,342.297240,203065,0,...,171.0,5.639544,0.005640,NaN,7/15/2020,2020-07-15 06:30:00,197.0,7.0,PR,3032160.0
43,A+,52,17640.0,1165,158235.0,1217,NaN,1670.201485,175875,5,...,987.0,93.451750,0.093452,1707.0,7/15/2020,2020-07-15 12:00:00,197.0,7.0,RI,1056160.0
44,A,1856,62245.0,6646,463738.0,8502,NaN,1194.698758,525983,0,...,998.0,19.155103,0.019155,23849.0,7/15/2020,2020-07-14 23:59:00,196.0,7.0,SC,5210100.0
45,B,80,7652.0,1299,85891.0,1379,NaN,847.372227,93543,8,...,111.0,12.291991,0.012292,6663.0,7/15/2020,2020-07-14 18:00:00,196.0,7.0,SD,903027.0
46,A,2273,69061.0,23512,1028612.0,25785,NaN,1001.235216,1097673,56,...,783.0,11.351807,0.011352,39857.0,7/15/2020,2020-07-15 15:00:00,197.0,7.0,TN,6897580.0
47,B,7307,282365.0,36212,2359834.0,43519,NaN,958.069102,2642199,0,...,3432.0,11.644833,0.011645,149276.0,7/15/2020,2020-07-15 17:00:00,197.0,7.0,TX,29472300.0
48,A+,413,30891.0,7146,401189.0,7559,NaN,941.190450,432080,25,...,233.0,7.099070,0.007099,18593.0,7/15/2020,2020-07-15 11:01:00,197.0,7.0,UT,3282120.0
49,A+,1084,73527.0,13048,771455.0,14132,382.0,852.367378,844982,58,...,1992.0,23.092413,0.023092,9527.0,7/15/2020,2020-07-14 17:00:00,196.0,7.0,VA,8626210.0
50,C,37,243.0,553,4637.0,590,199.0,NaN,4880,0,...,6.0,5.745751,0.005746,112.0,7/15/2020,2020-07-15 07:10:00,197.0,7.0,VI,104425.0
51,B,13,1318.0,721,77040.0,734,NaN,209.852228,78358,0,...,56.0,8.916331,0.008916,1104.0,7/15/2020,2020-07-15 00:00:00,197.0,7.0,VT,628061.0
52,B,547,42304.0,9413,675930.0,9960,NaN,542.560696,718234,10,...,1404.0,18.006695,0.018007,NaN,7/15/2020,2020-07-14 02:59:00,196.0,7.0,WA,7797100.0

In [57]:
tracking_clean.to_csv('tracking_clean.csv')